### 회원 가입

POST http://localhost:8080/signup
Content-Type: application/json

{
    "nickname": "닉네임",
    "email": "xxx@gmail.com",
    "password": "1234",
    "address": "경기도 수원시 영통구",
    "phoneNumber": "010-0000-0000"
}

### 로그인

POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "xxx@gmail.com",
  "password": "1234"
}

### 회원 수정

PATCH http://localhost:8080/member
Content-Type: application/json

{
  "nickname": "수정 닉네임",
  "email": "xxx@gmail.com",
  "password": "수정 1234",
  "address": "경기도 수원시 영통구",
  "phoneNumber": "010-0000-0000"
}

### 로그아웃

POST http://localhost:8080/logout


### 폐기물 이미지 업로드

POST http://localhost:8080/waste-management/image
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="wasteImage1.png"

< C:\Users\Administrator\Pictures\mssp\waste\wasteImage1.PNG
--WebAppBoundary--